### ISSUE TITLE
Mixed Content Block with ace.js

### ISSUE THREAD

**Issue by chuck-confluent** [michaelpeacock/kafka-sigma-streams#1]
Error: The `ace.js` isn't loading the text editor for sigma rules in the sigma streams UI when serving the UI on https.
```
Mixed Content: The page at 'https://8080-confluentinc-demosiemopt-0pt4at2be8n.ws-us34.gitpod.io/sigma_rules.html' was loaded over HTTPS, but requested an insecure script 'http://ajaxorg.github.io/ace-builds/src/ace.js'. This request has been blocked; the content must be served over HTTPS.
```

Proposed solution: change the following to retrieve over HTTPS rather than HTTP
- https://github.com/michaelpeacock/kafka-sigma-streams/blob/master/sigma-streams-ui/src/main/resources/static/sigma_rules.html#L91-L92

**Comment by chuck-confluent** [comment]
Alternatively if https isn't available, bring those js files into the project directly. It's github.io though, so https will be available.

**Comment by michaelpeacock** [comment]
Updated ace-builds to use https.

**Comment by chuck-confluent** [comment]
@michaelpeacock could you push a new docker image so I can get this deployed in the SIEM demo?
